defaults: &defaults
  working_directory: ~/repo
  macos:
    xcode: "10.0.0" # Node 10.11

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}
            - npm-packages-master
            - npm-packages
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save Package Cache
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to npm
          command: npm publish

tagged: &tagged
  filters:
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

any: &any
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build:
    jobs:
      - checkout:
          <<: *any
      - publish:
          <<: *tagged
          requires:
            - checkout